# Generated by Django 6.0.1 on 2026-02-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.FloatField(),
        ),
    ]
