# Generated by Django 6.0.1 on 2026-01-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('suspended', 'Suspended')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='poll',
            name='winning_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_polls', to='base.polloption'),
        ),
    ]
