# Generated by Django 6.0.1 on 2026-01-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pollcomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bet',
            name='shares',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.polloption'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.poll'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidity_b', models.FloatField(default=100.0)),
                ('yes_shares', models.FloatField(default=0.0)),
                ('no_shares', models.FloatField(default=0.0)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='base.poll')),
            ],
        ),
    ]
