# Generated by Django 6.0.1 on 2026-01-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_bet_unique_together_bet_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='base.polloption'),
        ),
    ]
