# Generated by Django 6.0.1 on 2026-01-10 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_bet_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='base.poll'),
        ),
    ]
