# Generated by Django 6.0.1 on 2026-01-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='liquidity_b',
            field=models.FloatField(default=500),
        ),
    ]
