# Generated by Django 6.0.1 on 2026-01-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_poll_winning_option_alter_poll_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='winning_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_polls', to='base.polloption'),
        ),
    ]
