# Generated by Django 6.0.1 on 2026-01-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_poll_winning_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='liquidity_b',
            field=models.FloatField(default=100.0),
        ),
    ]
