# Generated by Django 6.0.1 on 2026-01-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_market_liquidity_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketposition',
            name='no_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketposition',
            name='yes_spent',
            field=models.FloatField(default=0),
        ),
    ]
