# Generated by Django 6.0.1 on 2026-01-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_marketposition_no_spent_marketposition_yes_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_price', models.FloatField()),
                ('no_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='base.market')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
