# Generated by Django 6.0.1 on 2026-02-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='creator_choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
    ]
