# Generated by Django 6.0.1 on 2026-02-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_challenge_creator_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('bet_won', 'Bet Won'), ('bet_refunded', 'Bet Refunded'), ('poll_resolved', 'Poll Resolved'), ('challenge_accepted', 'Challenge Accepted'), ('challenge_won', 'Challenge Won'), ('challenge_lost', 'Challenge Lost'), ('challenge_cancelled', 'Challenge Cancelled')], max_length=30),
        ),
    ]
