# Generated by Django 6.0.1 on 2026-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.FloatField(),
        ),
    ]
