# Generated by Django 5.2.7 on 2026-03-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_bet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Open challenge anyone can accept'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='base.poll'),
        ),
        migrations.AddField(
            model_name='poll',
            name='resolution_criteria',
            field=models.TextField(blank=True, help_text='Conditions that must be met before this market can be resolved.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('bet_won', 'Bet Won'), ('bet_refunded', 'Bet Refunded'), ('poll_resolved', 'Poll Resolved'), ('challenge_accepted', 'Challenge Accepted'), ('challenge_won', 'Challenge Won'), ('challenge_lost', 'Challenge Lost'), ('challenge_cancelled', 'Challenge Cancelled'), ('challenge_received', 'Challenge Received'), ('market_challenge', 'Market Challenge')], max_length=30),
        ),
    ]
