# Generated by Django 5.2.7 on 2026-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_challenge_is_open_challenge_poll_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='market',
            name='shares',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='marketposition',
            name='option_shares',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='marketposition',
            name='option_spent',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='polloption',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='creator_choice',
            field=models.CharField(help_text='The option text the creator is backing', max_length=255),
        ),
    ]
