# Generated by Django 5.2.7 on 2026-04-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_challenge_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='resolution_criteria',
            field=models.TextField(blank=True, help_text='Conditions that must be met before this challenge can be resolved.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
